### RequestUserByID
GET http://{{host}}:{{port}}/{{user_id}}
Content-Type: application/json

### RequestUserByEmail
GET http://{{host}}:{{port}}/email/{{email}}
Content-Type: application/json



### RequestCreateUser-200
POST http://{{host}}:{{port}}
Content-Type: application/json
X-Request-ID: {{$random.uuid}}

{"email": "{{email}}","password": "{{password}}","name": "{{name}}","age": {{age}}}
> {%

    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 400");
    });
%}

### RequestCreateUser-400
POST http://{{host}}:{{port}}
Content-Type: application/json
X-Request-ID: {{$random.uuid}}

{"email": "{{email}}"}
> {%

    client.test("Bad Request", function() {
        client.assert(response.status === 400, "Response status is 400");
    });
 %}

### RequestUpdateUser-200
PUT http://{{host}}:{{port}}/{{user_id}}
Content-Type: application/json
X-Request-ID: {{$random.uuid}}

{"name": "{{name}}","age": {{age}}}
> {%

    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 400");
    });
%}


### RequestDeleteUser-200
DELETE http://{{host}}:{{port}}/{{user_id}}
Content-Type: application/json
X-Request-ID: {{$random.uuid}}

> {%

    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 400");
    });
%}

### RequestLoginUser-200
POST http://{{host}}:{{port}}/login
Content-Type: application/json
X-Request-ID: {{$random.uuid}}

{"email": "{{email}}","password": "{{password}}"}
> {%

    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 400");
    });
%}

### RequestLoginUser-400
POST http://{{host}}:{{port}}/login
Content-Type: application/json
X-Request-ID: {{$random.uuid}}

{"email": "{{email}}","password": "{{password_erro}}"}
> {%

    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 400");
    });
%}