// Code generated by MockGen. DO NOT EDIT.
// Source: model/service/user_interface.go
//
// Generated by this command:
//
//	mockgen -source=model/service/user_interface.go -destination=test/mocks/user_service_mock.go --package=mocks
//
// Package mocks is a generated GoMock package.
package mocks

import (
	rest_err "golang-basic/config/rest_err"
	model "golang-basic/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserDomainService is a mock of UserDomainService interface.
type MockUserDomainService struct {
	ctrl     *gomock.Controller
	recorder *MockUserDomainServiceMockRecorder
}

// MockUserDomainServiceMockRecorder is the mock recorder for MockUserDomainService.
type MockUserDomainServiceMockRecorder struct {
	mock *MockUserDomainService
}

// NewMockUserDomainService creates a new mock instance.
func NewMockUserDomainService(ctrl *gomock.Controller) *MockUserDomainService {
	mock := &MockUserDomainService{ctrl: ctrl}
	mock.recorder = &MockUserDomainServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDomainService) EXPECT() *MockUserDomainServiceMockRecorder {
	return m.recorder
}

// CreateService mocks base method.
func (m *MockUserDomainService) CreateService(arg0 model.UserDomainInterface) (model.UserDomainInterface, *rest_err.RestErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateService", arg0)
	ret0, _ := ret[0].(model.UserDomainInterface)
	ret1, _ := ret[1].(*rest_err.RestErr)
	return ret0, ret1
}

// CreateService indicates an expected call of CreateService.
func (mr *MockUserDomainServiceMockRecorder) CreateService(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateService", reflect.TypeOf((*MockUserDomainService)(nil).CreateService), arg0)
}

// DeleteService mocks base method.
func (m *MockUserDomainService) DeleteService(arg0 string) *rest_err.RestErr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteService", arg0)
	ret0, _ := ret[0].(*rest_err.RestErr)
	return ret0
}

// DeleteService indicates an expected call of DeleteService.
func (mr *MockUserDomainServiceMockRecorder) DeleteService(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteService", reflect.TypeOf((*MockUserDomainService)(nil).DeleteService), arg0)
}

// FindUserByEmailService mocks base method.
func (m *MockUserDomainService) FindUserByEmailService(email string) (model.UserDomainInterface, *rest_err.RestErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmailService", email)
	ret0, _ := ret[0].(model.UserDomainInterface)
	ret1, _ := ret[1].(*rest_err.RestErr)
	return ret0, ret1
}

// FindUserByEmailService indicates an expected call of FindUserByEmailService.
func (mr *MockUserDomainServiceMockRecorder) FindUserByEmailService(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmailService", reflect.TypeOf((*MockUserDomainService)(nil).FindUserByEmailService), email)
}

// FindUserByIDService mocks base method.
func (m *MockUserDomainService) FindUserByIDService(id string) (model.UserDomainInterface, *rest_err.RestErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByIDService", id)
	ret0, _ := ret[0].(model.UserDomainInterface)
	ret1, _ := ret[1].(*rest_err.RestErr)
	return ret0, ret1
}

// FindUserByIDService indicates an expected call of FindUserByIDService.
func (mr *MockUserDomainServiceMockRecorder) FindUserByIDService(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByIDService", reflect.TypeOf((*MockUserDomainService)(nil).FindUserByIDService), id)
}

// LoginService mocks base method.
func (m *MockUserDomainService) LoginService(domainInterface model.UserDomainInterface) (model.UserDomainInterface, string, *rest_err.RestErr) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginService", domainInterface)
	ret0, _ := ret[0].(model.UserDomainInterface)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*rest_err.RestErr)
	return ret0, ret1, ret2
}

// LoginService indicates an expected call of LoginService.
func (mr *MockUserDomainServiceMockRecorder) LoginService(domainInterface any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginService", reflect.TypeOf((*MockUserDomainService)(nil).LoginService), domainInterface)
}

// UpdateService mocks base method.
func (m *MockUserDomainService) UpdateService(arg0 string, arg1 model.UserDomainInterface) *rest_err.RestErr {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateService", arg0, arg1)
	ret0, _ := ret[0].(*rest_err.RestErr)
	return ret0
}

// UpdateService indicates an expected call of UpdateService.
func (mr *MockUserDomainServiceMockRecorder) UpdateService(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateService", reflect.TypeOf((*MockUserDomainService)(nil).UpdateService), arg0, arg1)
}
